version: "3.7"
services:
  app:
    build: ./src/
    image: "audeldiaz/todo-phoenix:1.9-alpine"
    restart: on-failure
    depends_on:
      - db
    volumes:
      - "./src/:/usr/src/myapp"
    command: mix phx.server
    env_file: .env

  db:
    image: postgres:11
    restart: on-failure
    env_file: .env

  nginx:
    image: nginx
    restart: on-failure
    depends_on:
      - app
    volumes:
      - "./nginx/dev.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
