version: "3.7"
services:
  app:
    build: src/
    image: "audeldiaz/todo-phoenix:1.9-alpine"
    depends_on:
      - db
    volumes:
      - "./src/:/usr/src/myapp"
    ports:
      - "4000:4000"
    command: mix phx.server
    env_file: .env

  db:
    image: postgres:11
    restart: on-failure
    env_file: .env