version: "3.7"
services:
  todo:
    build:
      context: ./todo/
      dockerfile: ../Dockerfile-prod
    image: "audeldiaz/todo-phoenix:1.9-alpine"
    restart: on-failure
    depends_on:
      - db
    volumes:
      - "./todo/:/usr/src/myapp"
    env_file: .env_prod

  note:
    build:
      context: ./note/
      dockerfile: ../Dockerfile-prod
    image: "audeldiaz/note-phoenix:1.9-alpine"
    restart: on-failure
    depends_on:
      - db
    volumes:
      - "./note/:/usr/src/myapp"
    env_file: .env_prod

  db:
    image: postgres:11
    restart: on-failure
    env_file: .env_prod

  nginx:
    image: nginx
    restart: on-failure
    depends_on:
      - todo
      - note
    volumes:
      - "./nginx/todo.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/note.conf:/etc/nginx/conf.d/note.conf"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
